name: scrapping data

on:
 schedule:
   - cron: '0 18 * * *' 

jobs: 
  autoscrape:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    
    - name: Install packages
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("RCurl")'
        R -e 'install.packages("vroom")'
    
    - name: Scrape
      run: Rscript 01_dowloand_data.R
   
    - name: Commit files
      run: |

        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add resources/*
        git commit -am "updated datasets $(date)"
        git push origin main
      
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
